ALTER TABLE "Site" ADD COLUMN "latitude" DOUBLE PRECISION,
ADD COLUMN "longitude" DOUBLE PRECISION,
ADD COLUMN "landmark" TEXT;

ALTER TABLE "ProgressUpdate" ADD COLUMN "latitude" DOUBLE PRECISION,
ADD COLUMN "longitude" DOUBLE PRECISION,
ADD COLUMN "accuracyM" INTEGER,
ADD COLUMN "distanceM" INTEGER;
